version: '3.8'

services:
  trading_app:
    build: .
    container_name: rep_2025_dev
    volumes:
      - .:/app  # Mount your code
    working_dir: /app
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
