name: trading-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-learn=1.1.3
  - scipy=1.10.1
  - ta-lib
  - matplotlib
  - numba
  - pip:
      - torch==2.1.0+cu118
      - torchvision==0.16.0+cu118
      - torchaudio==2.1.0+cu118
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - vectorbt==0.25.1
